openapi: 3.0.0
info:
  version: 1.0.0
  title: API Bingo
  description: API para el juego de bingo
  contact:
    name: Diego Acosta
    email: dguruz2108@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://yapqtndlxf.execute-api.us-east-1.amazonaws.com/desa
paths:
  /all-cards:
    get:
      summary: Get all cards generated
      responses:
        '200':
          description: All cards listed
          
        '500':
          description: Internal Error
  /create-game:
    post:
      summary: Create a new Bingo game
      responses:
        '201':
          description: Game created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gameId:
                    type: string
                    description: The ID of the newly created game
        '500':
          description: Internal Error
          
  /create-card:
    post:
      summary: Create a new Bingo card
      responses:
        '201':
          description: Card created successfully
        '500':
          description: Internal Error
      requestBody:
        description: JSON request to create a Bingo Card
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The player declaring Bingo
         
  /call-numbers:
    post:
      summary: Call numbers without repetition
      requestBody:
        description: JSON request to Call numbers
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                game_id:
                  type: string
                  description: The player declaring Bingo
      responses:
        '200':
          description: A new ball added
        '404':
          description: Game not found
  /check-winner:
    post:
      summary: Check if there is a winner
      responses:
        '200':
          description: ¡BINGOOOOOOOOO!
          
        '400':
          description: NO LUCK THIS TIME
      requestBody:
        description: JSON request to create a Bingo Card
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_game:
                  type: string
                  description: The player declaring Bingo
                id_card:
                  type: string
                  description: The player declaring Bingo
